# Generated by Django 4.0.3 on 2022-05-20 04:41

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('room_pw', models.IntegerField()),
                ('room_invited_code', models.CharField(max_length=50)),
                ('room_play_round', models.IntegerField()),
                ('room_round_limit_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QuizPlayers',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('auth', models.IntegerField(default=0)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizroom')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
