# Generated by Django 4.0.3 on 2022-06-02 18:30

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizroom_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizroom',
            name='room_user',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=220, size=10),
        ),
    ]
