# Generated by Django 4.0.3 on 2022-06-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_quizroom_room_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizroom',
            name='room_host',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
