# Generated by Django 4.0.3 on 2022-06-02 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizroom_room_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=10000)),
                ('user', models.CharField(max_length=100)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizroom')),
            ],
        ),
    ]
