# Generated by Django 4.0.3 on 2022-06-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
