# Generated by Django 4.0.3 on 2022-06-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_alter_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizplayers',
            name='player_score',
            field=models.IntegerField(default=0),
        ),
    ]
