# Generated by Django 4.0.3 on 2022-06-10 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_quizplayers_player_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizroom',
            name='room_invited_code',
        ),
        migrations.RemoveField(
            model_name='quizroom',
            name='room_pw',
        ),
    ]
